/**
 * Represents the two main sections of the Boys' Brigade.
 */
export type Section = 'company' | 'junior';

/**
 * Represents the squad numbers for the Company Section.
 */
export type Squad = 1 | 2 | 3;
/**
 * Represents the school year for members of the Company Section.
 */
export type SchoolYear = 8 | 9 | 10 | 11 | 12 | 13 | 14;

/**
 * Represents the squad numbers for the Junior Section.
 */
export type JuniorSquad = 1 | 2 | 3 | 4;
/**
 * Represents the school year (Primary school levels) for members of the Junior Section.
 */
export type JuniorYear = 'P4' | 'P5' | 'P6' | 'P7';

/**
 * Represents a single weekly mark entry for a member.
 * A score of -1 indicates absence.
 */
export interface Mark {
  /** The date of the meeting in 'YYYY-MM-DD' format. */
  date: string; 
  /** The total score for the night. -1 if absent. */
  score: number;
  /** (Junior Section only) The score for uniform inspection. */
  uniformScore?: number;
  /** (Junior Section only) The score for behaviour. */
  behaviourScore?: number;
}

/**
 * Represents a single member of the Boys' Brigade.
 */
export interface Boy {
  /** A unique identifier, generated by Firestore or a temporary one for offline creation. */
  id?: string;
  /** The full name of the member. */
  name: string;
  /** The squad number the member belongs to. */
  squad: Squad | JuniorSquad;
  /** The school year of the member. */
  year: SchoolYear | JuniorYear;
  /** An array of all recorded marks for the member. */
  marks: Mark[];
  /** A flag indicating if the member is a designated squad leader. */
  isSquadLeader?: boolean;
}

/**
 * Defines the types of actions that can be recorded in the audit log.
 */
export type AuditLogActionType = 'CREATE_BOY' | 'UPDATE_BOY' | 'DELETE_BOY' | 'REVERT_ACTION' | 'UPDATE_SETTINGS';

/**
 * Represents a single entry in the audit log, tracking changes made in the application.
 */
export interface AuditLog {
  /** A unique identifier for the log entry. */
  id?: string;
  /** The timestamp of when the action occurred (Unix milliseconds). */
  timestamp: number;
  /** The email of the user who performed the action. */
  userEmail: string;
  /** The type of action performed. */
  actionType: AuditLogActionType;
  /** A human-readable description of the action. */
  description: string;
  /** Data needed to revert the action (e.g., the state of an object before a change). */
  revertData: any;
  /** The ID of the original audit log that this REVERT_ACTION log is reverting. */
  revertedLogId?: string;
}

/**
 * Represents the main pages available in the application's navigation.
 */
export type Page = 'home' | 'weeklyMarks' | 'dashboard' | 'auditLog' | 'settings' | 'help';

/**
 * A specific view type for displaying an individual boy's marks page.
 * Includes the boy's ID to fetch the correct data.
 */
export interface BoyMarksPageView {
  page: 'boyMarks';
  boyId: string;
}

/**
 * A union type representing the current view of the application,
 * which can be a standard page or a more specific view like BoyMarksPageView.
 */
export type View = { page: Page } | BoyMarksPageView;

/**
 * Represents the settings specific to a section (Company or Junior).
 */
export interface SectionSettings {
  /** The day of the week the section meets (0 = Sunday, 1 = Monday, ..., 6 = Saturday). */
  meetingDay: number;
}

/**
 * Defines the types of toast notifications.
 */
export type ToastType = 'success' | 'error' | 'info';

/**
 * Represents a single toast notification message.
 */
export interface ToastMessage {
  id: string;
  message: string;
  type: ToastType;
}

/**
 * Defines the available sorting options for the member roster.
 */
export type SortByType = 'name' | 'marks' | 'attendance';