/**
 * Represents the two main sections of the Boys' Brigade.
 */
export type Section = 'company' | 'junior';

/**
 * Squad numbers are configured per section in settings.
 * Company historically used 1–3 and Junior 1–4.
 */
export type Squad = number;
/**
 * Represents the school year for members of the Company Section.
 */
export type SchoolYear = 8 | 9 | 10 | 11 | 12 | 13 | 14;

/**
 * Squad numbers are configured per section in settings.
 */
export type JuniorSquad = number;
/**
 * Represents the school year (Primary school levels) for members of the Junior Section.
 */
export type JuniorYear = 'P4' | 'P5' | 'P6' | 'P7';

/**
 * Represents a single weekly mark entry for a member.
 * A score of -1 indicates absence.
 */
export interface Mark {
  /** The date of the meeting in 'YYYY-MM-DD' format. */
  date: string; 
  /** The total score for the night. -1 if absent. */
  score: number;
  /** (Junior Section only) The score for uniform inspection. */
  uniformScore?: number;
  /** (Junior Section only) The score for behaviour. */
  behaviourScore?: number;
}

/**
 * Represents the weekly snapshot payload used for section-wide mark saves.
 */
export interface WeeklyMarksSnapshotEntry {
  memberId: string;
  mark: Mark | null;
}

/**
 * Represents a single member of the Boys' Brigade.
 */
export interface Boy {
  /** A unique identifier generated by Supabase. */
  id?: string;
  /** The full name of the member. */
  name: string;
  /** The squad number the member belongs to. */
  squad: Squad | JuniorSquad;
  /** The school year of the member. */
  year: SchoolYear | JuniorYear;
  /** An array of all recorded marks for the member. */
  marks: Mark[];
  /** A flag indicating if the member is a designated squad leader. */
  isSquadLeader?: boolean;
  /** Set when this live member was imported from a past-session archive row. */
  importedFromArchivedMemberId?: string | null;
}

/**
 * Represents the main pages available in the application's navigation.
 */
export type Page = 'home' | 'weeklyMarks' | 'dashboard' | 'archives' | 'settings' | 'accountSettings';

/**
 * A specific view type for displaying an individual boy's marks page.
 * Includes the boy's ID to fetch the correct data.
 */
export interface BoyMarksPageView {
  page: 'boyMarks';
  boyId: string;
}

/**
 * A union type representing the current view of the application,
 * which can be a standard page or a more specific view like BoyMarksPageView.
 */
export type View = { page: Page } | BoyMarksPageView;

/**
 * A squad configured for a section. `label` is an optional nickname; the number is what members store.
 */
export interface SectionSquad {
  number: number;
  label: string | null;
}

/**
 * Represents the settings specific to a section (Company or Junior).
 */
export interface SectionSettings {
  /** The day of the week the section meets (0 = Sunday, 1 = Monday, ..., 6 = Saturday). */
  meetingDay: number;
  /** Ordered list of squads staff can assign members to. */
  squads: SectionSquad[];
}

/**
 * Defines the types of toast notifications.
 */
export type ToastType = 'success' | 'error' | 'info';

/**
 * Represents a single toast notification message.
 */
export interface ToastMessage {
  id: string;
  message: string;
  type: ToastType;
}

/**
 * Defines the available sorting options for the member roster.
 */
export type SortByType = 'name' | 'marks' | 'attendance';

/**
 * Defines the possible roles a user can have in the application.
 */
export type UserRole = 'admin' | 'captain' | 'officer';

/**
 * Minimal authenticated user shape for Supabase auth.
 */
export interface AppUser {
  id: string;
  email: string;
}

/**
 * Combines an authenticated user with their assigned application role.
 */
export interface UserWithRole {
  user: AppUser;
  role: UserRole;
}
